name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
      - run: go test

  build:
    name: Build binary
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        goos:
          - 'darwin'
          - 'linux'
          - 'windows'
        goarch:
          - 'amd64'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build ./cmd/client
